/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sd.advanced.coding;

import com.sd.advanced.coding.examples.*;
import com.sd.advanced.coding.exercises.*;
import com.sd.advanced.coding.util.CliUtil;

import java.util.Map;

import static com.sd.advanced.coding.Constants.EXAMPLE_ARG;
import static com.sd.advanced.coding.Constants.EXERCISE_ARG;
import static java.lang.String.format;

public class App {
    public static void main(String[] args) throws InterruptedException {
        Map<String, String> arguments = CliUtil.parseArguments(args);
        if (arguments.get(EXERCISE_ARG) != null) {
            String exercise = arguments.get(EXERCISE_ARG);
            new App().runExercise(Integer.parseInt(exercise));
        } else if (arguments.get(EXAMPLE_ARG) != null) {
            String example = arguments.get(EXAMPLE_ARG);
            new App().runExample(example);
        } else {
            System.out.printf("--%s - was not specified. Usage example: --%s [exercise number] . Program will be terminated%n", EXERCISE_ARG, EXERCISE_ARG);
            System.out.println("or");
            System.out.printf("--%s - was not specified. Usage example: --%s [example number] . Program will be terminated%n", EXAMPLE_ARG, EXAMPLE_ARG);
            System.exit(1);
        }
    }

    public void runExercise(int exerciseNumber) {
        System.out.printf("Will run exercise: %d%n", exerciseNumber);

        switch(exerciseNumber) {
            case 1: {
                new Exercise1().run();
                break;
            }
            case 2: {
                new Exercise2().run();
                break;
            }
            case 3: {
                new Exercise3().run();
                break;
            }
            case 4: {
                new Exercise4().run();
                break;
            }
            case 5: {
                new Exercise5().run();
                break;
            }
            case 6: {
                new Exercise6().run();
                break;
            }
            default:
                System.out.printf("No exercise found with number %d%n", exerciseNumber);
        }
    }

    public void runExample(String exampleName) throws InterruptedException {
        System.out.printf("Will run example: %s%n", exampleName);

        switch(exampleName) {
            case "threads": {
                new ExampleThreads().run();
                break;
            }
            case "sync": {
                new ExampleSync().run();
                break;
            }
            case "deadlock": {
                new ExampleDeadlock().run();
                break;
            }
            case "lambda": {
                new ExampleLambdaExpression().run();
                break;
            }
            case "aggregators": {
                new ExampleAggregators().run();
                break;
            }
            case "encapsulation": {
                new ExampleEncapsulation().run();
                break;
            }
            default:
                System.out.printf("No example found with number %s%n", exampleName);
        }
    }
}
